// src/components/SEO.jsx
import { Helmet } from "react-helmet-async";
import { useLocation } from "react-router-dom";

const seoData = {
  "/": { title: "BNS Holidays - Best Tour Packages", description: "Explore best tour packages across India and the world. Book now with BNS Holidays." },
  "/villa": { title: "Villa Stays | BNS Holidays", description: "Luxury villa stays with BNS Holidays." },
  "/visa": { title: "Visa Services | BNS Holidays", description: "Visa assistance services with BNS Holidays." },
  "/Pages/europe": { title: "Europe Tour Packages | BNS Holidays", description: "Best Europe tour packages. France, Italy, Switzerland and more." },
  "/Pages/australia": { title: "Australia Tour Packages | BNS Holidays", description: "Best Australia tour packages. Sydney, Melbourne, Gold Coast and more." },
  "/Pages/canada": { title: "Canada Tour Packages | BNS Holidays", description: "Best Canada tour packages. Toronto, Vancouver, Niagara Falls and more." },
  "/Pages/usa": { title: "USA Tour Packages | BNS Holidays", description: "Best USA tour packages. New York, California, Las Vegas and more." },
  "/usa-landing": { title: "USA Tours | BNS Holidays", description: "Book best USA tour packages starting at great prices." },
  "/ny-washington": { title: "New York & Washington Tour | BNS Holidays", description: "Explore New York and Washington DC with BNS Holidays." },
  "/california": { title: "California Tour Package | BNS Holidays", description: "Best California tour packages with hotel, meals & sightseeing." },
  "/vegas-grand": { title: "Vegas & Grand Canyon Tour | BNS Holidays", description: "Las Vegas and Grand Canyon tour packages." },
  "/luxury-usa": { title: "Luxury USA Tour | BNS Holidays", description: "Premium luxury USA tour packages. Book now." },
  "/aus-landing": { title: "Best Australia Tours | BNS Holidays", description: "Book Australia tour packages with BNS Holidays." },
  "/sydney-melbourne": { title: "Sydney & Melbourne Tour | BNS Holidays", description: "Explore Sydney and Melbourne with BNS Holidays." },
  "/gold-coast": { title: "Gold Coast Tour | BNS Holidays", description: "Gold Coast tour packages with BNS Holidays." },
  "/great-ocean": { title: "Great Ocean Road Tour | BNS Holidays", description: "Great Ocean Road tour packages. Book now." },
  "/luxury-aus": { title: "Luxury Australia Tour | BNS Holidays", description: "Premium luxury Australia tour packages." },
  "/canada-landing": { title: "Best Canada Tours | BNS Holidays", description: "Book Canada tour packages with BNS Holidays." },
  "/toronto-niagara": { title: "Toronto & Niagara Tour | BNS Holidays", description: "Toronto and Niagara Falls tour packages." },
  "/vancouver-victoria": { title: "Vancouver & Victoria Tour | BNS Holidays", description: "Vancouver and Victoria tour packages." },
  "/rocky-tour": { title: "Rocky Mountain Tour Canada | BNS Holidays", description: "Canadian Rockies tour packages. Book now." },
  "/luxury-canada": { title: "Luxury Canada Tour | BNS Holidays", description: "Premium luxury Canada tour packages." },
  "/europe-landing": { title: "Best Europe Tours | BNS Holidays", description: "Book Europe tour packages with BNS Holidays." },
  "/france-swiss": { title: "France & Switzerland Tour | BNS Holidays", description: "France and Switzerland combo tour packages." },
  "/italy-tour": { title: "Italy Tour Package | BNS Holidays", description: "Best Italy tour packages with BNS Holidays." },
  "/eastern-europe": { title: "Eastern Europe Tour | BNS Holidays", description: "Eastern Europe tour packages. Book now." },
  "/luxury-europe": { title: "Luxury Europe Tour | BNS Holidays", description: "Premium luxury Europe tour packages." },
  "/Pages/NewZealand": { title: "New Zealand Tour Packages | BNS Holidays", description: "Best New Zealand tour packages with BNS Holidays." },
  "/nz-landing": { title: "Best New Zealand Tours | BNS Holidays", description: "Book New Zealand tour packages with BNS Holidays." },
  "/Pages/Thailand": { title: "Thailand Tour Packages | BNS Holidays", description: "Best Thailand tour packages. Bangkok, Phuket, Krabi and more." },
  "/Pages/Singapore": { title: "Singapore Tour Packages | BNS Holidays", description: "Best Singapore tour packages with BNS Holidays." },
  "/thailand-landing": { title: "Best Thailand Tours | BNS Holidays", description: "Book Thailand tour packages with BNS Holidays." },
  "/bangkok-pattaya": { title: "Bangkok & Pattaya Tour | BNS Holidays", description: "Bangkok and Pattaya tour packages." },
  "/phuket-krabi": { title: "Phuket & Krabi Tour | BNS Holidays", description: "Phuket and Krabi tour packages." },
  "/thailand-luxury": { title: "Luxury Thailand Tour | BNS Holidays", description: "Premium luxury Thailand tour packages." },
  "/best-of-singapore": { title: "Best of Singapore Tour | BNS Holidays", description: "Explore the best of Singapore with BNS Holidays." },
  "/singapore-sentosa": { title: "Singapore Sentosa Tour | BNS Holidays", description: "Singapore Sentosa Island tour packages." },
  "/universal-singapore": { title: "Universal Studios Singapore | BNS Holidays", description: "Universal Studios Singapore tour packages." },
  "/luxury-singapore": { title: "Luxury Singapore Tour | BNS Holidays", description: "Premium luxury Singapore tour packages." },
  "/Pages/malaysia": { title: "Malaysia Tour Packages | BNS Holidays", description: "Best Malaysia tour packages. KL, Langkawi, Penang and more." },
  "/malaysia-landing": { title: "Best Malaysia Tours | BNS Holidays", description: "Book Malaysia tour packages with BNS Holidays." },
  "/kl-genting": { title: "KL & Genting Tour | BNS Holidays", description: "Kuala Lumpur and Genting tour packages." },
  "/langkawi": { title: "Langkawi Tour | BNS Holidays", description: "Langkawi island tour packages." },
  "/penang": { title: "Penang Tour | BNS Holidays", description: "Penang tour packages with BNS Holidays." },
  "/luxury-malaysia": { title: "Luxury Malaysia Tour | BNS Holidays", description: "Premium luxury Malaysia tour packages." },
  "/Pages/bali": { title: "Bali Tour Packages | BNS Holidays", description: "Best Bali tour packages. Ubud, Kuta, beaches and more." },
  "/bali-landing": { title: "Best Bali Tours | BNS Holidays", description: "Book Bali tour packages with BNS Holidays." },
  "/ubud-kuta": { title: "Ubud & Kuta Bali Tour | BNS Holidays", description: "Ubud and Kuta Bali tour packages." },
  "/bali-beach": { title: "Bali Beach Tour | BNS Holidays", description: "Bali beach holiday packages." },
  "/bali-adventure": { title: "Bali Adventure Tour | BNS Holidays", description: "Bali adventure tour packages." },
  "/luxury-bali": { title: "Luxury Bali Tour | BNS Holidays", description: "Premium luxury Bali tour packages." },
  "/Pages/dubai": { title: "Dubai Tour Packages | BNS Holidays", description: "Best Dubai tour packages. Desert safari, Burj Khalifa and more." },
  "/dubai-landing": { title: "Best Dubai Tours | BNS Holidays", description: "Book Dubai tour packages with BNS Holidays." },
  "/dubai-abu": { title: "Dubai & Abu Dhabi Tour | BNS Holidays", description: "Dubai and Abu Dhabi combo tour packages." },
  "/desert-safari": { title: "Desert Safari Dubai | BNS Holidays", description: "Dubai desert safari tour packages." },
  "/luxury-dubai": { title: "Luxury Dubai Tour | BNS Holidays", description: "Premium luxury Dubai tour packages." },
  "/Pages/abu-dhabi": { title: "Abu Dhabi Tour Packages | BNS Holidays", description: "Best Abu Dhabi tour packages." },
  "/abu-landing": { title: "Best Abu Dhabi Tours | BNS Holidays", description: "Book Abu Dhabi tour packages." },
  "/abu-city": { title: "Abu Dhabi City Tour | BNS Holidays", description: "Abu Dhabi city tour packages." },
  "/abu-culture": { title: "Abu Dhabi Cultural Tour | BNS Holidays", description: "Abu Dhabi cultural tour packages." },
  "/abu-ferrari": { title: "Ferrari World Abu Dhabi | BNS Holidays", description: "Ferrari World Abu Dhabi tour packages." },
  "/abu-luxury": { title: "Luxury Abu Dhabi Tour | BNS Holidays", description: "Premium luxury Abu Dhabi tour packages." },
  "/Pages/france": { title: "France Tour Packages | BNS Holidays", description: "Best France tour packages. Paris, Nice, French Riviera and more." },
  "/france-landing": { title: "Best France Tours | BNS Holidays", description: "Book France tour packages with BNS Holidays." },
  "/paris-nice": { title: "Paris & Nice Tour | BNS Holidays", description: "Paris and Nice tour packages." },
  "/french-riviera": { title: "French Riviera Tour | BNS Holidays", description: "French Riviera tour packages." },
  "/luxury-france": { title: "Luxury France Tour | BNS Holidays", description: "Premium luxury France tour packages." },
  "/Pages/germany": { title: "Germany Tour Packages | BNS Holidays", description: "Best Germany tour packages. Berlin, Munich, Bavarian Alps and more." },
  "/germany-landing": { title: "Best Germany Tours | BNS Holidays", description: "Book Germany tour packages with BNS Holidays." },
  "/berlin-munich": { title: "Berlin & Munich Tour | BNS Holidays", description: "Berlin and Munich tour packages." },
  "/bavarian-alps": { title: "Bavarian Alps Tour | BNS Holidays", description: "Bavarian Alps tour packages." },
  "/luxury-germany": { title: "Luxury Germany Tour | BNS Holidays", description: "Premium luxury Germany tour packages." },
  "/Pages/italy": { title: "Italy Tour Packages | BNS Holidays", description: "Best Italy tour packages. Rome, Venice, Florence and more." },
  "/italy-landing": { title: "Best Italy Tours | BNS Holidays", description: "Book Italy tour packages with BNS Holidays." },
  "/rome-venice": { title: "Rome & Venice Tour | BNS Holidays", description: "Rome and Venice tour packages." },
  "/florence-tour": { title: "Florence Tour | BNS Holidays", description: "Florence tour packages." },
  "/amalfi-coast": { title: "Amalfi Coast Tour | BNS Holidays", description: "Amalfi Coast tour packages." },
  "/luxury-italy": { title: "Luxury Italy Tour | BNS Holidays", description: "Premium luxury Italy tour packages." },
  "/Pages/switzerland": { title: "Switzerland Tour Packages | BNS Holidays", description: "Best Switzerland tour packages. Zurich, Lucerne, Swiss Alps and more." },
  "/switzerland-landing": { title: "Best Switzerland Tours | BNS Holidays", description: "Book Switzerland tour packages." },
  "/zurich-lucerne": { title: "Zurich & Lucerne Tour | BNS Holidays", description: "Zurich and Lucerne tour packages." },
  "/interlaken": { title: "Interlaken Tour | BNS Holidays", description: "Interlaken tour packages." },
  "/swiss-alps": { title: "Swiss Alps Tour | BNS Holidays", description: "Swiss Alps tour packages." },
  "/luxury-switzerland": { title: "Luxury Switzerland Tour | BNS Holidays", description: "Premium luxury Switzerland tour packages." },
  "/Pages/hungary": { title: "Hungary Tour Packages | BNS Holidays", description: "Best Hungary tour packages. Budapest, Danube Cruise and more." },
  "/hungary-landing": { title: "Best Hungary Tours | BNS Holidays", description: "Book Hungary tour packages." },
  "/budapest-landing": { title: "Budapest Tour | BNS Holidays", description: "Budapest tour packages." },
  "/danube-cruise": { title: "Danube Cruise Tour | BNS Holidays", description: "Danube Cruise tour packages." },
  "/luxury-hungary": { title: "Luxury Hungary Tour | BNS Holidays", description: "Premium luxury Hungary tour packages." },
  "/Pages/poland": { title: "Poland Tour Packages | BNS Holidays", description: "Best Poland tour packages with BNS Holidays." },
  "/poland-landing": { title: "Best Poland Tours | BNS Holidays", description: "Book Poland tour packages." },
  "/Pages/manali": { title: "Manali Tour Packages | BNS Holidays", description: "Best Manali tour packages. Rohtang Pass, adventure and more." },
  "/manali-landing": { title: "Best Manali Tours | BNS Holidays", description: "Book Manali tour packages." },
  "/rohtang-landing": { title: "Rohtang Pass Tour | BNS Holidays", description: "Rohtang Pass tour packages." },
  "/manali-adventure": { title: "Manali Adventure Tour | BNS Holidays", description: "Manali adventure tour packages." },
  "/luxury-manali": { title: "Luxury Manali Tour | BNS Holidays", description: "Premium luxury Manali tour packages." },
  "/Pages/shimla": { title: "Shimla Tour Packages | BNS Holidays", description: "Best Shimla tour packages. Kufri, adventure and more." },
  "/shimla-landing": { title: "Best Shimla Tours | BNS Holidays", description: "Book Shimla tour packages." },
  "/shimla-kufri": { title: "Shimla & Kufri Tour | BNS Holidays", description: "Shimla and Kufri tour packages." },
  "/shimla-adventure": { title: "Shimla Adventure Tour | BNS Holidays", description: "Shimla adventure tour packages." },
  "/luxury-shimla": { title: "Luxury Shimla Tour | BNS Holidays", description: "Premium luxury Shimla tour packages." },
  "/Pages/spiti": { title: "Spiti Valley Tour Packages | BNS Holidays", description: "Best Spiti Valley tour packages." },
  "/spiti-landing": { title: "Best Spiti Tours | BNS Holidays", description: "Book Spiti Valley tour packages." },
  "/spiti-adventure": { title: "Spiti Adventure Tour | BNS Holidays", description: "Spiti Valley adventure tour packages." },
  "/chandratal": { title: "Chandratal Lake Tour | BNS Holidays", description: "Chandratal Lake tour packages." },
  "/luxury-spiti": { title: "Luxury Spiti Tour | BNS Holidays", description: "Premium luxury Spiti Valley tour packages." },
  "/Pages/srinagar": { title: "Srinagar Tour Packages | BNS Holidays", description: "Best Srinagar tour packages. Houseboat, Gulmarg and more." },
  "/srinagar-landing": { title: "Best Srinagar Tours | BNS Holidays", description: "Book Srinagar tour packages." },
  "/gulmarg": { title: "Gulmarg Tour | BNS Holidays", description: "Gulmarg tour packages." },
  "/houseboat": { title: "Houseboat Srinagar Tour | BNS Holidays", description: "Srinagar houseboat tour packages." },
  "/luxury-kashmir": { title: "Luxury Kashmir Tour | BNS Holidays", description: "Premium luxury Kashmir tour packages." },
  "/Pages/gulmarg": { title: "Gulmarg Tour Packages | BNS Holidays", description: "Best Gulmarg tour packages. Skiing, snow adventure and more." },
  "/gulmarg-snow-adventure": { title: "Gulmarg Snow Adventure | BNS Holidays", description: "Gulmarg snow adventure tour packages." },
  "/gulmarg-ski-experience": { title: "Gulmarg Ski Experience | BNS Holidays", description: "Gulmarg skiing experience packages." },
  "/luxury-gulmarg": { title: "Luxury Gulmarg Tour | BNS Holidays", description: "Premium luxury Gulmarg tour packages." },
  "/Pages/pahalgam": { title: "Pahalgam Tour Packages | BNS Holidays", description: "Best Pahalgam tour packages." },
  "/pahalgam-landing": { title: "Best Pahalgam Tours | BNS Holidays", description: "Book Pahalgam tour packages." },
  "/pahalgam-valley": { title: "Pahalgam Valley Tour | BNS Holidays", description: "Pahalgam valley tour packages." },
  "/pahalgam-adventure": { title: "Pahalgam Adventure Tour | BNS Holidays", description: "Pahalgam adventure tour packages." },
  "/luxury-pahalgam": { title: "Luxury Pahalgam Tour | BNS Holidays", description: "Premium luxury Pahalgam tour packages." },
  "/Pages/munnar": { title: "Munnar Tour Packages | BNS Holidays", description: "Best Munnar tour packages. Tea estates, adventure and more." },
  "/munnar-landing": { title: "Best Munnar Tours | BNS Holidays", description: "Book Munnar tour packages." },
  "/munnar-alleppey": { title: "Munnar & Alleppey Tour | BNS Holidays", description: "Munnar and Alleppey combo tour packages." },
  "/munnar-adventure": { title: "Munnar Adventure Tour | BNS Holidays", description: "Munnar adventure tour packages." },
  "/luxury-munnar": { title: "Luxury Munnar Tour | BNS Holidays", description: "Premium luxury Munnar tour packages." },
  "/Pages/alleppey": { title: "Alleppey Tour Packages | BNS Holidays", description: "Best Alleppey houseboat tour packages." },
  "/alleppey-landing": { title: "Best Alleppey Tours | BNS Holidays", description: "Book Alleppey tour packages." },
  "/houseboat-alleppey": { title: "Alleppey Houseboat Tour | BNS Holidays", description: "Alleppey houseboat tour packages." },
  "/alleppey-kumarakom": { title: "Alleppey & Kumarakom Tour | BNS Holidays", description: "Alleppey and Kumarakom tour packages." },
  "/luxury-alleppey": { title: "Luxury Alleppey Tour | BNS Holidays", description: "Premium luxury Alleppey tour packages." },
  "/Pages/kochi": { title: "Kochi Tour Packages | BNS Holidays", description: "Best Kochi tour packages." },
  "/kochi-landing": { title: "Best Kochi Tours | BNS Holidays", description: "Book Kochi tour packages." },
  "/kochi-munnar": { title: "Kochi & Munnar Tour | BNS Holidays", description: "Kochi and Munnar combo tour packages." },
  "/kochi-cultural": { title: "Kochi Cultural Tour | BNS Holidays", description: "Kochi cultural tour packages." },
  "/luxury-kochi": { title: "Luxury Kochi Tour | BNS Holidays", description: "Premium luxury Kochi tour packages." },
  "/Pages/ooty": { title: "Ooty Tour Packages | BNS Holidays", description: "Best Ooty tour packages. Coonoor, adventure and more." },
  "/ooty-landing": { title: "Best Ooty Tours | BNS Holidays", description: "Book Ooty tour packages." },
  "/ooty-coonoor": { title: "Ooty & Coonoor Tour | BNS Holidays", description: "Ooty and Coonoor tour packages." },
  "/ooty-adventure": { title: "Ooty Adventure Tour | BNS Holidays", description: "Ooty adventure tour packages." },
  "/luxury-ooty": { title: "Luxury Ooty Tour | BNS Holidays", description: "Premium luxury Ooty tour packages." },
  "/Pages/chennai": { title: "Chennai Tour Packages | BNS Holidays", description: "Best Chennai tour packages." },
  "/chennai-landing": { title: "Best Chennai Tours | BNS Holidays", description: "Book Chennai tour packages." },
  "/chennai-mahabalipuram": { title: "Chennai & Mahabalipuram Tour | BNS Holidays", description: "Chennai and Mahabalipuram tour packages." },
  "/chennai-cultural": { title: "Chennai Cultural Tour | BNS Holidays", description: "Chennai cultural tour packages." },
  "/luxury-chennai": { title: "Luxury Chennai Tour | BNS Holidays", description: "Premium luxury Chennai tour packages." },
  "/Pages/gangtok": { title: "Gangtok Tour Packages | BNS Holidays", description: "Best Gangtok tour packages. Nathula Pass, adventure and more." },
  "/gangtok-landing": { title: "Best Gangtok Tours | BNS Holidays", description: "Book Gangtok tour packages." },
  "/gangtok-nathula": { title: "Gangtok & Nathula Tour | BNS Holidays", description: "Gangtok and Nathula Pass tour packages." },
  "/gangtok-adventure": { title: "Gangtok Adventure Tour | BNS Holidays", description: "Gangtok adventure tour packages." },
  "/luxury-gangtok": { title: "Luxury Gangtok Tour | BNS Holidays", description: "Premium luxury Gangtok tour packages." },
  "/Pages/guwahati": { title: "Guwahati Tour Packages | BNS Holidays", description: "Best Guwahati tour packages. Shillong, adventure and more." },
  "/guwahati-landing": { title: "Best Guwahati Tours | BNS Holidays", description: "Book Guwahati tour packages." },
  "/guwahati-shillong": { title: "Guwahati & Shillong Tour | BNS Holidays", description: "Guwahati and Shillong tour packages." },
  "/guwahati-adventure": { title: "Guwahati Adventure Tour | BNS Holidays", description: "Guwahati adventure tour packages." },
  "/luxury-guwahati": { title: "Luxury Guwahati Tour | BNS Holidays", description: "Premium luxury Guwahati tour packages." },
  "/Pages/jaipur": { title: "Jaipur Tour Packages | BNS Holidays", description: "Best Jaipur tour packages. Udaipur, adventure and more." },
  "/jaipur-landing": { title: "Best Jaipur Tours | BNS Holidays", description: "Book Jaipur tour packages." },
  "/jaipur-udaipur": { title: "Jaipur & Udaipur Tour | BNS Holidays", description: "Jaipur and Udaipur combo tour packages." },
  "/jaipur-adventure": { title: "Jaipur Adventure Tour | BNS Holidays", description: "Jaipur adventure tour packages." },
  "/luxury-jaipur": { title: "Luxury Jaipur Tour | BNS Holidays", description: "Premium luxury Jaipur tour packages." },
  "/Pages/udaipur": { title: "Udaipur Tour Packages | BNS Holidays", description: "Best Udaipur tour packages." },
  "/udaipur-landing": { title: "Best Udaipur Tours | BNS Holidays", description: "Book Udaipur tour packages." },
  "/udaipur-mountabu": { title: "Udaipur & Mount Abu Tour | BNS Holidays", description: "Udaipur and Mount Abu tour packages." },
  "/udaipur-adventure": { title: "Udaipur Adventure Tour | BNS Holidays", description: "Udaipur adventure tour packages." },
  "/luxury-udaipur": { title: "Luxury Udaipur Tour | BNS Holidays", description: "Premium luxury Udaipur tour packages." },
  "/Pages/northgoa": { title: "North Goa Tour Packages | BNS Holidays", description: "Best North Goa tour packages. Beaches, party, adventure and more." },
  "/northgoa-landing": { title: "Best North Goa Tours | BNS Holidays", description: "Book North Goa tour packages." },
  "/northgoa-party": { title: "North Goa Party Tour | BNS Holidays", description: "North Goa party tour packages." },
  "/northgoa-adventure": { title: "North Goa Adventure Tour | BNS Holidays", description: "North Goa adventure tour packages." },
  "/luxury-northgoa": { title: "Luxury North Goa Tour | BNS Holidays", description: "Premium luxury North Goa tour packages." },
  "/Pages/southgoa": { title: "South Goa Tour Packages | BNS Holidays", description: "Best South Goa tour packages." },
  "/southgoa-landing": { title: "Best South Goa Tours | BNS Holidays", description: "Book South Goa tour packages." },
  "/southgoa-escape": { title: "South Goa Escape Tour | BNS Holidays", description: "South Goa peaceful escape tour packages." },
  "/southgoa-adventure": { title: "South Goa Adventure Tour | BNS Holidays", description: "South Goa adventure tour packages." },
  "/luxury-southgoa": { title: "Luxury South Goa Tour | BNS Holidays", description: "Premium luxury South Goa tour packages." },
  "/karnataka-tours": { title: "Karnataka Tour Packages | BNS Holidays", description: "Best Karnataka tour packages. Bangalore, Mysore, Coorg, Hampi and more." },
  "/bangalore-landing": { title: "Bangalore Tour Package | BNS Holidays", description: "Best Bangalore tour packages starting from ₹12,000." },
  "/mysore-landing": { title: "Mysore Tour Package | BNS Holidays", description: "Best Mysore tour packages starting from ₹15,000." },
  "/coorg-landing": { title: "Coorg Tour Package | BNS Holidays", description: "Best Coorg tour packages starting from ₹18,000." },
  "/hampi-landing": { title: "Hampi Tour Package | BNS Holidays", description: "Best Hampi tour packages starting from ₹20,000." },
};

function SEO() {
  // ✅ useLocation works correctly with HashRouter
  const { pathname } = useLocation();

  const seo = seoData[pathname] || {
    title: "BNS Holidays - Best Tour Packages",
    description: "Explore best tour packages across India and the world with BNS Holidays.",
  };

  return (
    <Helmet>
      <title>{seo.title}</title>
      <meta name="description" content={seo.description} />
      <meta name="robots" content="index, follow" />
      <meta property="og:title" content={seo.title} />
      <meta property="og:description" content={seo.description} />
      <meta property="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={seo.title} />
      <meta name="twitter:description" content={seo.description} />
    </Helmet>
  );
}

export default SEO;